"""Generate MCP server project tree."""
from __future__ import annotations

from pathlib import Path


def generate_server(name: str, out: Path, tools: int = 2) -> Path:
    safe = "".join(c if c.isalnum() or c in "-_" else "-" for c in name).strip("-") or "mcp-server"
    root = out / safe
    pkg = safe.replace("-", "_")
    (root / "src" / pkg / "tools").mkdir(parents=True, exist_ok=True)
    (root / "tests").mkdir(parents=True, exist_ok=True)

    (root / "pyproject.toml").write_text(
        f'''[project]
name = "{safe}"
version = "0.1.0"
requires-python = ">=3.11"

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"
''',
        encoding="utf-8",
    )
    (root / "README.md").write_text(
        f"# {safe}\n\nGenerated by x4-mcp-server-starter.\n\nNot production-ready until tests, security, and registry validation pass.\n",
        encoding="utf-8",
    )
    (root / "src" / pkg / "__init__.py").write_text(f'__version__ = "0.1.0"\n', encoding="utf-8")
    (root / "src" / pkg / "server.py").write_text(
        '''"""MCP server entry (scaffold)."""
from __future__ import annotations

def health() -> dict:
    return {"status": "ok"}
''',
        encoding="utf-8",
    )
    for i in range(1, max(1, tools) + 1):
        (root / "src" / pkg / "tools" / f"tool_{i}.py").write_text(
            f'"""Tool {i} scaffold."""\n\ndef run(**kwargs):\n    return {{"tool": {i}, "ok": True}}\n',
            encoding="utf-8",
        )
    (root / "tests" / "test_health.py").write_text(
        f"from {pkg}.server import health\n\ndef test_health():\n    assert health()[\"status\"] == \"ok\"\n",
        encoding="utf-8",
    )
    (root / "mcp.json").write_text(
        f'{{\n  "name": "{safe}",\n  "version": "0.1.0",\n  "transports": ["stdio"]\n}}\n',
        encoding="utf-8",
    )
    return root
